type User {
  id: ID! @skipAuth
  name: String! @skipAuth
}

extend type Query {
  me: User
  user(id: ID!): User
  users: [User]
}

extend type Mutation {
  createUser(data: CreateUserInput!): CreateUserPayload @skipAuth
}

input CreateUserInput {
  sub: String!
  name: String
  email: EmailAddress!
}

type CreateUserPayload {
  user: User @skipAuth
}
