name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            set -e
            cd /var/www/app
            git pull
            fnm install $(cat .node-version)
            fnm use $(cat .node-version)
            pnpm install
            pnpm api gen
            pnpm lint
            pnpm api build
            pnpm web build
            pm2 stop api && pm2 delete api
            pm2 stop web && pm2 delete web
            pnpm api db:deploy
            pm2 start --name api 'pnpm api start -k 3000 --wait-ready --listen-timeout 10000'
            pm2 start --name web 'pnpm web start'
          EOF
